USE [master]
GO

/****** Object:  Database [Dbo_englishClub]    Script Date: 4.09.2022 18:43:16 ******/
CREATE DATABASE [Dbo_englishClub]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Dbo_englishClub', FILENAME = N'D:\Programlar\MSSQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\Dbo_englishClub.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Dbo_englishClub_log', FILENAME = N'D:\Programlar\MSSQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\Dbo_englishClub_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Dbo_englishClub].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Dbo_englishClub] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET ARITHABORT OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Dbo_englishClub] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Dbo_englishClub] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Dbo_englishClub] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Dbo_englishClub] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET RECOVERY FULL 
GO

ALTER DATABASE [Dbo_englishClub] SET  MULTI_USER 
GO

ALTER DATABASE [Dbo_englishClub] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Dbo_englishClub] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Dbo_englishClub] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Dbo_englishClub] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Dbo_englishClub] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Dbo_englishClub] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Dbo_englishClub] SET  READ_WRITE 
GO


